# Challenge: Promotions

In this challenge, you'll develop codes to parse and analyze data returned from another API on Zalando such as [Promos homme (Men's Promotions)
](https://www.zalando.fr/promo-homme/) or [Promos femme (Women's Promotions)](https://www.zalando.fr/promo-femme/). The workflow is almost the same as in the guided lesson but you'll work with different data.

## Obtaining the link

Wrote your codes in the cell below to obtain the data from the API endpoint you choose. A recap of the workflow:

1. Examine the webpages and choose one that you want to work with.

1. Use Google Chrome's DevTools to inspect the XHR network requests. Find out the API endpoint that serves data to the webpage.

1. Test the API endpoint in the browser to verify its data.

1. Change the page number offset of the API URL to test if it's working.

In [9]:
import json
import requests
import pandas as pd
from pandas.io.json import json_normalize
import urllib.request

In [10]:
# your code here
api_url ='https://www.zalando.fr/api/catalog/articles?categories=promo-sport-homme&limit=84&offset=0&sort=popularity'

## Reading the data

In the next cell, use Python to obtain data from the API endpoint you chose in the previous step. Workflow:

1. Import libraries.

1. Define the initial API endpoint URL.

1. Make request to obtain data of the 1st page. Flatten the data and store it in an empty object variable.

1. Find out the total page count in the 1st page data.

1. Use a FOR loop to make requests for the additional pages from 2 to page count. Append the data of each additional page to the flatterned data object.

1. Print and review the data you obtained.

In [11]:
# your code here
def f_page():
    url = 'https://www.zalando.fr/api/catalog/articles'
    params = {'categories':'promo-sport-homme', 'limit':84, 'offset':0, 'sort':'popularity'}
    headers={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'}
    response = requests.get(url, headers=headers)
    fp = urllib.request.urlopen(url)
    mybytes = fp.read()
    response = mybytes.decode("utf8")
    fp.close()

    return json.loads(response)

In [13]:
#f_page()

In [16]:
total_n = zalando['pagination']['page_count']
total_n

106

In [22]:
dataframe=pd.DataFrame()

for page in range(total_n2):
    url='https://www.zalando.fr/api/catalog/articles?categories=promo-sport-homme&limit=84&offset='+str(page*84)+'&sort=popularity'
    headers={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'}
    response = requests.get(url, headers=headers)
    fp = urllib.request.urlopen(url)
    mybytes = fp.read()
    response = mybytes.decode("utf8")
    fp.close()
    zalando = json.loads(response)
    df_zala=pd.json_normalize(zalando['articles'])
    df_zala.set_index('sku', inplace=True)
    dataframe=dataframe.append(df_zala)

In [20]:
dataframe

,name,sizes,url_key,media,brand_name,is_premium,family_articles,flags,product_group,delivery_promises,price.original,price.promotional,price.has_different_prices,price.has_different_original_prices,price.has_different_promotional_prices,price.has_discount_on_selected_sizes_only,amount,outfits
sku,,,,,,,,,,,,,,,,,,
L0642G018-Q11,veste en sweat zippée - black/corrida/pitch chine,"[XS, M, L, 3XL]",lacoste-sport-veste-en-sweat-zippee-blackcorri...,[{'path': 'L0/64/2G/01/8Q/11/L0642G018-Q11@8.j...,Lacoste Sport,False,[],"[{'key': 'campaign', 'value': '-20% EXTRA', 't...",clothing,[],"120,00 €","84,00 €",True,False,True,False,NaN,NaN
L0642D003-K14,Polo - haiti blue,"[S, M, L, XL, XXL]",lacoste-sport-polo-haiti-blue-l0642d003-k14,[{'path': 'L0/64/2D/00/3K/14/L0642D003-K14@10....,Lacoste Sport,False,[],"[{'key': 'campaign', 'value': '-20% EXTRA', 't...",clothing,[],"80,00 €","56,00 €",False,False,False,False,NaN,NaN
N1242E1DK-N11,DRY ACADEMY PANT - Pantalon de survêtement - c...,"[S, M, L, XL, XXL]",nike-performance-dry-academy-pant-pantalon-de-...,[{'path': 'N1/24/2E/1D/KN/11/N1242E1DK-N11@12....,Nike Performance,False,[],"[{'key': 'campaign', 'value': '-20% EXTRA', 't...",clothing,[],"49,95 €","24,95 €",False,False,False,False,NaN,NaN
AD542G0OI-E11,Sweat à capuche - yellow,"[S, M, L, XL, XXL, 3XL]",adidas-performance-sweatshirt-yellow-ad542g0oi...,[{'path': 'AD/54/2G/0O/IE/11/AD542G0OI-E11@9.j...,adidas Performance,False,[],"[{'key': 'discountRate', 'value': '-20%', 'tra...",clothing,[],"39,95 €","31,95 €",False,False,False,False,NaN,NaN
L0642D04I-K12,TENNIS BLOCK - T-shirt imprimé - obscurity/nav...,"[XS, S, M, L, XL, XXL, 3XL, 4XL]",lacoste-sport-tennis-block-t-shirt-de-sport-l0...,[{'path': 'L0/64/2D/04/IK/12/L0642D04I-K12@13....,Lacoste Sport,False,[],"[{'key': 'campaign', 'value': '-20% EXTRA', 't...",clothing,[],"64,95 €","41,95 €",True,False,True,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S1642K004-K11,CRYO - Survêtement - navy,"[S, M, L, XL, XXL]",sergio-tacchini-cryo-tracksuit-survetement-nav...,[{'path': 'S1/64/2K/00/4K/11/S1642K004-K11@32....,sergio tacchini,False,[],"[{'key': 'campaign', 'value': '-20% EXTRA', 't...",clothing,[],"99,99 €","89,99 €",False,False,False,False,NaN,NaN
AS142A0OU-C11,GT-1000 9 - Chaussures de running stables - me...,"[41.5, 42, 42.5, 43.5, 44, 44.5, 45, 46.5, 48]",asics-gt-1000-9-chaussures-de-running-stables-...,[{'path': 'AS/14/2A/0O/UC/11/AS142A0OU-C11@2.j...,ASICS,False,[],"[{'key': 'campaign', 'value': '-20% EXTRA', 't...",shoe,[],"119,95 €","71,95 €",True,False,True,False,299 g,NaN
QU142L049-K12,NEW CENTURION - Sac de voyage - light grey hea...,[One Size],quiksilver-new-centurion-sac-de-voyage-light-g...,[{'path': 'QU/14/2L/04/9K/12/QU142L049-K12@17....,Quiksilver,False,[],"[{'key': 'campaign', 'value': '-20% EXTRA', 't...",accessoires,[],"99,99 €","59,99 €",False,False,False,False,NaN,NaN
SMD42I000-G11,SEAMLESS SPYDER - T-shirt imprimé - bordeaux,"[M, L, XL, XXL]",smilodox-seamless-spyder-t-shirt-imprime-smd42...,[{'path': 'SM/D4/2I/00/0G/11/SMD42I000-G11@8.j...,Smilodox,False,[],"[{'key': 'campaign', 'value': '-20% EXTRA', 't...",clothing,[],"29,95 €","8,95 €",False,False,False,False,NaN,NaN
HI242A030-Q12,WARRIOR - Chaussures de marche - black/blue,"[39, 42, 44, 45, 46]",hi-tec-warrior-chaussures-de-marche-hi242a030-q12,[{'path': 'HI/24/2A/03/0Q/12/HI242A030-Q12@9.j...,Hi-Tec,False,[],"[{'key': 'campaign', 'value': '-20% EXTRA', 't...",shoe,[],"69,95 €","62,95 €",False,False,False,False,NaN,NaN

## Bonus

Extract the following information from the data:

* The trending brand.

* The product(s) with the highest discount.

* The sum of discounts of all goods (sum_discounted_prices divided by sum_original_prices).

In [23]:
# your code here
#trending brand
dataframe.groupby('brand_name').count().nlargest(1,'name')

,name,sizes,url_key,media,is_premium,family_articles,flags,product_group,delivery_promises,price.original,price.promotional,price.has_different_prices,price.has_different_original_prices,price.has_different_promotional_prices,price.has_discount_on_selected_sizes_only,amount,outfits
brand_name,,,,,,,,,,,,,,,,,
Nike Performance,125,125,125,125,125,125,125,125,125,125,125,125,125,125,125,12,2

In [24]:
#I converted to float
# your code
dataframe["price.original"]=dataframe["price.original"].str.replace("€","").str.replace(',', '.').str.strip()
dataframe["price.original"]=pd.to_numeric(dataframe["price.original"])

In [25]:
#I converted to float
dataframe["price.promotional"]=dataframe["price.promotional"].str.replace("€","").str.replace(',', '.').str.strip()
dataframe["price.promotional"]=pd.to_numeric(dataframe["price.promotional"])

In [26]:
#The different between original and promotional price, the result will be the promotional one
dataframe["price_disc"]= dataframe["price.original"] - dataframe["price.promotional"]

In [27]:
#The product(s) with the highest discount
dataframe.groupby('brand_name').sum().nlargest(1,'price.promotional')

,is_premium,price.original,price.promotional,price.has_different_prices,price.has_different_original_prices,price.has_different_promotional_prices,price.has_discount_on_selected_sizes_only,price_disc
brand_name,,,,,,,,
Lacoste Sport,0.0,9737.9,6932.64,48.0,1.0,47.0,0.0,2805.26

In [28]:
dataframe["sum_discounts"]= dataframe["price.promotional"] / dataframe["price.original"]

In [29]:
#The sum of discounts of all goods (sum_discounted_prices divided by sum_original_prices).
dataframe.groupby('brand_name').sum()

,is_premium,price.original,price.promotional,price.has_different_prices,price.has_different_original_prices,price.has_different_promotional_prices,price.has_discount_on_selected_sizes_only,price_disc,sum_discounts
brand_name,,,,,,,,,
'47,0.0,119.95,119.95,0.0,0.0,0.0,0.0,0.00,1.000000
ASICS,0.0,2360.90,1747.83,14.0,0.0,14.0,0.0,613.07,16.829046
ASICS SportStyle,0.0,169.95,118.95,1.0,0.0,1.0,0.0,51.00,0.699912
BIDI BADU,0.0,295.65,164.55,0.0,0.0,0.0,0.0,131.10,3.444553
Björn Borg,0.0,209.75,121.25,0.0,0.0,0.0,0.0,88.50,3.010283
...,...,...,...,...,...,...,...,...,...
Volcom,0.0,140.00,98.00,0.0,0.0,0.0,0.0,42.00,1.400000
Ziener,0.0,49.95,32.45,0.0,0.0,0.0,0.0,17.50,0.649650
adidas Golf,0.0,167.90,109.10,0.0,0.0,0.0,0.0,58.80,1.499678
adidas Performance,0.0,7569.47,5208.47,68.0,5.0,64.0,0.0,2361.00,85.939978
sergio tacchini,0.0,264.88,237.28,3.0,1.0,2.0,0.0,27.60,3.599716